#系统配置
system:
  host: 0.0.0.0
  port: 8080

#数据库配置
database:
  db_path: ./database/sqlite/video.db

#Redis配置
redis:
  host: 192.168.0.9
  port: 6379
  password: '123456'
  db: 0

gofound:
  host: 192.168.0.9
  port: 5678
